# Generated by Django 5.0.14 on 2026-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('gadgets', 'Gadgets'), ('home', 'Home & Living')], default='electronics', max_length=50),
        ),
    ]
